'use strict';

// Browser cookies for a download: which site a link needs, and keeping only
// that site's lines of a cookie file.

const test = require('node:test');
const assert = require('node:assert/strict');
const { cookieSite, cookiesFor } = require('../src/cookies');

test('a link\'s site: the domain itself, YouTube for its short links and Spotify lists', () => {
  assert.equal(cookieSite('https://www.youtube.com/watch?v=abc'), 'youtube.com');
  assert.equal(cookieSite('https://music.youtube.com/playlist?list=x'), 'youtube.com');
  assert.equal(cookieSite('youtu.be/abc'), 'youtube.com');
  assert.equal(cookieSite('https://open.spotify.com/playlist/x'), 'youtube.com');
  assert.equal(cookieSite('spotify:album:abc'), 'youtube.com');
  assert.equal(cookieSite('https://soundcloud.com/a/b'), 'soundcloud.com');
  assert.equal(cookieSite('https://artist.bandcamp.com/album/x'), 'bandcamp.com');
  assert.equal(cookieSite('https://www.bbc.co.uk/sounds/play/x'), 'bbc.co.uk');
  assert.equal(cookieSite('not a link'), '');
});

test('only the site\'s cookies are kept, subdomains and HttpOnly ones included', () => {
  const jar = [
    '# Netscape HTTP Cookie File',
    '# This file is generated by yt-dlp.  Do not edit.',
    '',
    '.youtube.com\tTRUE\t/\tTRUE\t1793519874\tSAPISID\tv1',
    'music.youtube.com\tFALSE\t/\tTRUE\t1793519874\tPREF\tv2',
    '#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t1793519874\tHSID\tv3',
    '.google.com\tTRUE\t/\tTRUE\t1793519874\tNID\tv4',
    '.notyoutube.com\tTRUE\t/\tTRUE\t1793519874\tX\tv5',
    'garbage line',
  ].join('\n');
  const kept = cookiesFor(jar, 'youtube.com');
  assert.match(kept, /^# Netscape HTTP Cookie File\n/);
  assert.deepEqual(kept.trim().split('\n').slice(1).map((l) => l.split('\t')[5]), ['SAPISID', 'PREF', 'HSID']);
  assert.equal(cookiesFor(jar, 'example.org'), '');
  assert.equal(cookiesFor(jar, ''), '');
});
